### ISSUE TITLE
ModuleNotFoundError: No module named 'em'

### ISSUE THREAD

**Issue by dzy666fly** [AntoineRichard/OmniLRS#36]
Hi, it's me again :laughing:

After native installing, command `omni/pkg/isaac-sim-4.1.0/python.sh run.py` produced an error as follows (but issac sim seems to run successfully.):
```
[14.333s] Simulation App Starting
2024-10-17 09:15:59 [14,449ms] [Warning] [omni.kvdb.plugin] Disabling key-value database because another kit process is locking it
[19.338s] app ready
[21.010s] Simulation App Startup Complete
[21.038s] [ext: omni.isaac.ros2_bridge-2.31.4] startup
2024-10-17 09:16:06 [21,081ms] [Warning] [omni.isaac.ros2_bridge.plugin] Support for ROS 2 Foxy is deprecated and will be removed in a future release
[21.119s] Attempting to load system rclpy
[21.135s] rclpy loaded
[2024-10-17 17:16:11,574][rosidl_generator_py][DEBUG] - Failed to import modules for generating Python structures:
Traceback (most recent call last):
  File "IsaacSim-ros_workspaces/build_ws/foxy/foxy_ws/install/lib/python3.10/site-packages/rosidl_generator_py/__init__.py", line 23, in <module>
    from .generate_py_impl import generate_py
  File "IsaacSim-ros_workspaces/build_ws/foxy/foxy_ws/install/lib/python3.10/site-packages/rosidl_generator_py/generate_py_impl.py", line 21, in <module>
    from rosidl_cmake import convert_camel_case_to_lower_case_underscore
  File "IsaacSim-ros_workspaces/build_ws/foxy/foxy_ws/install/lib/python3.10/site-packages/rosidl_cmake/__init__.py", line 22, in <module>
    import em
ModuleNotFoundError: No module named 'em'

mesh update took 1560.65 ms
```

Well, I tried to solve it with Google, but found nothing useful. I observe that `em` has been installed in the default python3.8 environment (system version is ubuntu 20.04), and it is so wired that omniverse with ros2 needs python3.10, so maybe this makes error.

So does this error matter? If so, how can I solve this error?

Thank u so much again again.

**Comment by AntoineRichard** [comment]
Hi there,

No worries!

This is fine.

Cheers,

Antoine
